<a href="https://colab.research.google.com/github/sri6703/ML/blob/main/basicpythoncodes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
import pandas as pd
from numpy.linalg import eig

1.

In [ ]:
tp=("aman", "222", 777, 400.4)
print(tp)

('aman', '222', 777, 400.4)


2.

In [ ]:
dt={ "rollno":"62" , "fname":"srinithi" , "lname":"rajasekaran" , "dob": "13-12-2002"}
print(dt)

{'rollno': '62', 'fname': 'srinithi', 'lname': 'rajasekaran', 'dob': '13-12-2002'}


In [ ]:
dt.values()

dict_values(['62', 'srinithi', 'rajasekaran', '13-12-2002'])

In [ ]:
dt.keys()

dict_keys(['rollno', 'fname', 'lname', 'dob'])

3.

In [ ]:
np.random.seed() 
np.random.random((3,3))

array([[0.92983022, 0.76238923, 0.41341098],
       [0.86885625, 0.85738823, 0.12465216],
       [0.31314316, 0.26604149, 0.05923094]])

4.

In [ ]:
x=np.random.uniform(0.0,1.0)
print(x)
y=abs(-1234)
print(y)

0.6027633760716439
1234


5.

In [ ]:
x=np.random.randint(20,90)
print(x)

32


6.

In [ ]:
st=[11, 12, 13,14, 15]
x=random.sample(st,3)
print(x)

[13, 14, 11]


In [ ]:
random.shuffle(st)
print(st)

[15, 12, 13, 11, 14]


In [ ]:
y=random.choice(st)
print(y)

11


7.

In [ ]:
f=open("king.txt",'w')
f.write("The King is Dead, Long Live The King")
f=open("king.txt",'r')
print(f.read())


The King is Dead, Long Live The King


8.

In [ ]:
x=int(input("enter the mark"))
if x>90 :
  gr='A'
elif x>80 :
    gr='B'
elif x>70 :
    gr='C'
elif x>50 :
    gr='D'
else :
    gr='E'
print("grade for the given mark is :",gr)


enter the mark45
grade for the given mark is : E


In [ ]:
lt=[]
print("enter 4 values")
for i in range (0,4):
  a=int(input())
  lt.append(a)
sum=0
for i in range (0,4):
  sum=sum+lt[i]
print("sum of all the umbers is:" , sum)

  

enter 4 values
1
2
3
4
sum of all the umbers is: 10


In [ ]:
#counting untill the entered value is not 5 
lt=[1,2,3,4,5]
sz=len(lt)
count=0
for i in range (0,sz):
  if lt[i]!= 5 :
    count=count+1
    continue
  else:
    break
print(count)


4


In [ ]:
#prining a number in backwards
x=int(input("enter a number"))
n=x
c=1
while n>0 :
  print("digit",c,":",n%10)
  n=int(n/10)
  c=c+1



enter a number104
digit 1 : 4
digit 2 : 0
digit 3 : 1


9.

In [ ]:
sr="The King is Dead, Long Live The King"
print("printing the entire string:")
print(sr)
print("Print first character of the string:")
print(sr[0])
print("Print characters starting from 3rd to 5th")
print(sr[3:6])
print("Print string starting from 3rd character")
print(sr[3:])
print("Split the words:")
sr.split()

printing the entire string:
The King is Dead, Long Live The King
Print first character of the string:
T
Print characters starting from 3rd to 5th
 Ki
Print string starting from 3rd character
 King is Dead, Long Live The King
Split the words:


['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']

10.

In [ ]:
lt=[1,4,5,8]
print(lt[0:2])

[1, 4]


11.

In [ ]:
ar=np.array([[1,2,3],[4,5,6]])
print(ar)
print(ar[0][1])

[[1 2 3]
 [4 5 6]]
2


12.

In [ ]:
print(ar[1,0:3])
ar.flatten()


[4 5 6]


array([1, 2, 3, 4, 5, 6])

In [ ]:
print("length of the array :",len(ar))

length of the array : 2


13.

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,99])
att=arr.reshape(5,2)
print(att)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 99]]


In [ ]:
at=att.transpose()
print(at)

[[ 1  3  5  7  9]
 [ 2  4  6  8 99]]


14.

In [ ]:
lt=[1,2,3]
ars=np.array(lt)
print(ars)

[1 2 3]


15.

In [ ]:
at=np.full((2,5),9)
print(at)

[[9 9 9 9 9]
 [9 9 9 9 9]]


16.

In [ ]:
art=np.array([2,4,5])
sum=0
n=len(art)
for i in range (0,n):
  sum=sum+art[i]
print(sum)

11


17.

In [ ]:
art=np.array([77,74,75])
pro=1
n=len(art)
for i in range (0,n):
  pro=pro*art[i]
print(pro)

427350


18.

In [ ]:
arry=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("mean :",arry.mean())
print("variance :",arry.var())
print("min :",arry.min())
print("max :",arry.max())
print("argmin :",arry.argmin())
print("argmax :",arry.argmax())
print("standard deviation :",arry.std())
print("median :",np.median(arry))

mean : 12.461538461538462
variance : 367.32544378698225
min : 1
max : 56
argmin : 1
argmax : 12
standard deviation : 19.165736192147232
median : 2.0


19.

In [ ]:
are=np.array([1, 1, 4, 5, 5, 5, 7])
arrt=np.unique(are)
arrt.sort()
print(arrt)

[1 4 5 7]


20.

In [ ]:
a1=np.array([1,2,3])
a2=np.array([0,1,1])
ans=np.dot(a1,a2)
print(ans)

5


21.

In [ ]:
mat=np.array([[2,-12],[1,-5]])
val,vec=eig(mat)
print("eigen value: ",val)
print("eigen vector: ",vec)

eigen value:  [-1. -2.]
eigen vector:  [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
