<a href="https://colab.research.google.com/github/sri6703/ML/blob/main/pythonex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
p=input("enter value 1")
t=input("enter value 2")
r=input("enter value 3")
p=int(p)
t=int(t)
r=int(r)
a=pow(p*(1+r/100),t)
ci=a-p
print(ci)

enter value 11
enter value 22
enter value 32
0.04039999999999999


In [ ]:
a=[]
n=int(input("enter the number of elements"))
for i in range (0,n):
  a.append(input())
for i in  a:
  c=0
  for j in a:
    if (i==j):
      c=c+1
  print("percentage of the string", i,"in the list is :")
  perc=(c/n)*100
  print(perc)




enter the number of elements3
sri
sri
dfg
percentage of the string sri in the list is :
66.66666666666666
percentage of the string sri in the list is :
66.66666666666666
percentage of the string dfg in the list is :
33.33333333333333


In [ ]:
def divcheck( n) :
	temp = n
	while (temp > 0) :
		dig = temp % 10
		if n % dig !=0 :
			return False
		temp =temp//10
	return True
n = int(input())
if (divcheck(n)) :
	print("Yes")
else :
	print("No" )

345
No


In [ ]:
num=int(input())
ch=0
b=bin(num)
n=len(b)-1
m=2
while(ch==0 and m<n and n>1):
  if(b[m]==b[n]):
    ch=0
  else:
    ch=1
  m=m+1
  n=n-1
if(ch==0):
  print("yes")
else :
  print("no")


  




10
no


In [ ]:
num=[]
print("enter n")
n=int(input())
for i in range (0,n):
  num.append(input())

num.sort(reverse=True)
print(num[1])


enter n
4
1
2
3
4
3


In [ ]:
import numpy as np
  
# 3D Array    
array = np.random.randint(0,10,size=(4,5,2))
print("values","\n", array);

values 
 [[[2 7]
  [6 2]
  [9 9]
  [6 7]
  [6 7]]

 [[7 6]
  [8 7]
  [5 0]
  [6 6]
  [1 0]]

 [[9 0]
  [1 3]
  [1 7]
  [1 5]
  [0 2]]

 [[3 2]
  [7 6]
  [5 6]
  [5 9]
  [2 8]]]


In [ ]:
import numpy as np
c=[11.56,90.89,-18.06]
centi=np.array(c)
print("TEMPERATURE IN F:",np.round((9*centi/5 + 32),2))

TEMPERATURE IN F: [ 52.81 195.6   -0.51]


In [ ]:
import numpy as np    


x = np.array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])
print(x)
print("\nNumber of dimensions:")
print(x.ndim)
print("Number of elements:")
print(x.size)
print("Number of bytes for each element in the said array:")
print(x.itemsize)

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]

Number of dimensions:
2
Number of elements:
12
Number of bytes for each element in the said array:
8


In [ ]:
import numpy as np
x=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,5,4,2]])
print(x[0:2, 1:3])

[[2 3]
 [6 7]]
